version: '3.8'

services:
  shihiütv-core:
    image: Kulapichia/shihiütv:latest
    container_name: shihiütv-core
    restart: unless-stopped
    ports:
      - '3133:3000'
    dns:
      - 8.8.8.8
      - 1.1.1.1
      - 8.8.4.4
    dns_search:
      - .
    dns_opt:
      - ndots:1
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1
      - net.ipv6.conf.default.disable_ipv6=1
    environment:
      - USERNAME=root
      - PASSWORD=<您的shihiütv强密码>  # <--- 必须修改
      - NEXT_PUBLIC_STORAGE_TYPE=kvrocks
      - KVROCKS_URL=redis://shihiütv-kvrocks:6666
      - NEXT_PUBLIC_ENABLE_REGISTER=true
      - SHOW_CONTENT_FILTER=true
      - NEXT_PUBLIC_SITE_NAME=shihiütv
      # Sightengine审核服务
      - SIGHTENGINE_API_USER=您的Sightengine_API_User  # <--- 必须修改
      - SIGHTENGINE_API_SECRET=您的Sightengine_API_Secret  # <--- 必须修改
      # 百度智能云审核服务
      - BAIDU_API_KEY=您的百度云API_Key  # <--- 必须修改
      - BAIDU_SECRET_KEY=您的百度云Secret_Key  # <--- 必须修改

    networks:
      - shihiütv-network
    depends_on:
      - shihiütv-kvrocks
    # 如需自定义配置，可挂载文件
    # volumes:
      # - ./route.js:/app/.next/server/app/api/admin/user/route.js
  shihiütv-kvrocks:
    image: apache/kvrocks
    container_name: shihiütv-kvrocks
    restart: unless-stopped
    volumes:
      - kvrocks-data:/var/lib/kvrocks
    networks:
      - shihiütv-network


  m3u-editor:
    image: sparkison/m3u-editor:latest
    container_name: m3u-editor
    restart: unless-stopped
    ports:
      # 将容器的 36400 端口映射到服务器的 36400 端口
      - "36400:36400" # 应用主端口
      # 将容器的 36800 端口映射到服务器的 36800 端口
      - "36800:36800" # Websockets/广播端口
    
    volumes:
      # 将服务器当前目录下的 data 文件夹映射到容器内，用于持久化配置
      - ./data:/var/www/config
      # 使用名为 pgdata 的 Docker 卷来持久化 PostgreSQL 数据库数据
      - pgdata:/var/lib/postgresql/data
      
    environment:
      # --- 基本应用配置 ---
      - TZ=Asia/Shanghai  # 建议设置为您所在的时区，例如 Asia/Shanghai
      # 关键：APP_URL 必须是您的服务器公网 IP 和应用端口
      - APP_URL=http://<您的公网IP或域名>:36400  # <--- 必须修改
      
      # --- Websockets (Reverb) 配置 ---
      # 关键：REVERB_HOST 必须是您的服务器公网 IP，以便浏览器能够连接
      - REVERB_HOST=<您的公网IP或域名>             # <--- 必须修改
      - REVERB_SCHEME=https  # 如果您没有配置HTTPS，请使用http
      # --- 启用并配置内置 PostgreSQL 数据库 ---
      - ENABLE_POSTGRES=true               # 启用内置的 PostgreSQL 实例
      - DB_CONNECTION=pgsql                # 告诉应用连接类型为 pgsql
      - DB_HOST=localhost                  # 应用连接内部数据库时使用 localhost
      # --- 数据库凭证 (请务必修改密码) ---
      # 以下 PG_ 和 DB_ 的值必须保持一致
      - PG_DATABASE=m3ue
      - DB_DATABASE=m3ue
      
      - PG_USER=m3ue
      - DB_USERNAME=m3ue
      
      # 重要：请将下面的 "YourStrongPasswordHere" 替换为您自己的强密码
      - PG_PASSWORD=<您的m3u数据库强密码>       # <--- 必须修改
      - DB_PASSWORD=<您的m3u数据库强密码>       # <--- 必须修改
      
      - PG_PORT=5432
      - DB_PORT=5432
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
      - JELLYFIN_PublishedServerUrl=http://<您的公网IP> # <--- 必须修改
    volumes:
      - /path/to/jellyfin/library:/config
      - /path/to/tvseries:/data/tvshows
      - /path/to/movies:/data/movies
    ports:
      - 8096:8096
      - 8920:8920
      - 7359:7359/udp
      - 1900:1900/udp
    restart: unless-stopped

  watchtower:
    image: containrrr/watchtower
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_POLL_INTERVAL=300
    command: ""

# 全局卷定义
volumes:
  kvrocks-data: {} 
  pgdata: {}

networks:
  shihiütv-network:
    driver: bridge
