name: Build & Push Docker image to Docker Hub

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Docker Tag (e.g., latest, v1.2.3)'
        required: false
        default: 'latest'
        type: string
      force_rebuild:
        description: 'Force rebuild without using cache'
        required: false
        default: false
        type: boolean
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

env:
  IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/shiyutv
  REGISTRY: docker.io

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  actions: write
  packages: write

jobs:
  build-and-push:
    name: 🚀 Build & Push Multi-Platform Image
    runs-on: ubuntu-latest
    
    steps:
      - name: ⚡ Maximize build space
        run: |
          sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc
          sudo apt-get clean
          df -h

      - name: 📥 Checkout source code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      # Node.js 构建环境
      - name: ⚙️ Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: 📦 Setup pnpm
        uses: pnpm/action-setup@v4
      - name: 📦 Install dependencies
        run: pnpm install
      - name: 📜 Generate version and changelog
        run: node scripts/convert-changelog.js

      # Docker 环境
      - name: 🎯 Setup QEMU for multi-platform builds
        uses: docker/setup-qemu-action@v3

      - name: 🔧 Setup Docker Buildx for advanced features
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: |
            image=moby/buildkit:buildx-stable-1
            network=host

      - name: 🔐 Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: 🏷️ Extract intelligent Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_NAME }}
          tags: |
            # 方式一：手动触发时，使用输入的 tag，如果为空则默认为 'latest'
            type=raw,value=${{ github.event.inputs.tag || 'latest' }},enable=${{ github.event_name == 'workflow_dispatch' }}         
            # 方式二：当推送到【默认分支】(无论是 main 还是 master)时，强制打上 'latest' 标签。
            # 这是最关键的修正，它比之前的方法更可靠。
            type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', github.event.repository.default_branch) }}
            # 方式三：为每一次构建都生成一个基于 commit SHA 的唯一标签
            type=sha,prefix=sha-,format=short

      # 核心构建 - 统一原子操作，增强缓存策略
      - name: 🚀 Build and push multi-platform image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          # 只在非 pull_request 事件时推送
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          # 只使用 GitHub Actions 自带的缓存 (GHA Cache)。
          cache-from: type=gha,scope=multiarch-${{ github.workflow }}
          cache-to: type=gha,mode=max,scope=multiarch-${{ github.workflow }}
          # force_rebuild 时禁用缓存
          no-cache: ${{ github.event.inputs.force_rebuild == 'true' }}
          # 性能优化配置
          provenance: false
          sbom: false
          build-args: |
            BUILDKIT_INLINE_CACHE=1

  # 清理任务
  cleanup:
    runs-on: ubuntu-latest
    needs: [build-and-push]
    if: always()
    steps:
      - name: 🧹 Cleanup workflow runs
        uses: Mattraks/delete-workflow-runs@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          retain_days: 2
          keep_minimum_runs: 3
