name: Build & Push Docker image to Docker Hub

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Docker Tag'
        required: false
        default: 'latest'
        type: string
      force_rebuild:
        description: 'Force rebuild without using cache'
        required: false
        default: false
        type: boolean
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

env:
  IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/shiyutv
  REGISTRY: docker.io

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  actions: write

jobs:
  build-and-push:
    name: Build & Push Multi-Platform Image
    runs-on: ubuntu-latest
    
    steps:
      - name: Maximize build space
        run: |
          sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc
          sudo apt-get clean
          df -h

      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      # Node.js 构建环境
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Install dependencies
        run: pnpm install

      - name: Generate version and changelog
        run: node scripts/convert-changelog.js

      # Docker 环境
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: |
            image=moby/buildkit:buildx-stable-1
            network=host

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=${{ github.event.inputs.tag || 'latest' }}
          labels: |
            maintainer=${{ github.actor }}
            org.opencontainers.image.source=${{ github.server_url }}/${{ github.repository }}

      # 核心构建 - 统一原子操作，增强缓存策略
      - name: Build and push multi-platform image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          # 增强缓存策略 - 多架构特定缓存
          cache-from: |
            type=gha,scope=multiarch-${{ github.workflow }}
            type=registry,ref=${{ env.IMAGE_NAME }}:buildcache-multiarch
          cache-to: |
            type=gha,mode=max,scope=multiarch-${{ github.workflow }}
            type=registry,ref=${{ env.IMAGE_NAME }}:buildcache-multiarch,mode=max
          # force_rebuild 时禁用缓存
          no-cache: ${{ github.event.inputs.force_rebuild == 'true' }}
          # 性能优化配置
          provenance: false
          sbom: false
          build-args: |
            BUILDKIT_INLINE_CACHE=1
          # 优化输出
          outputs: type=registry,push=true

  # 清理任务
  cleanup:
    runs-on: ubuntu-latest
    needs: [build-and-push]
    if: always()
    steps:
      - name: Cleanup workflow runs
        uses: Mattraks/delete-workflow-runs@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          retain_days: 0
          keep_minimum_runs: 2
